<div id="info-login">
<!--    <img src="/img/log/dashboard.JPG" width="600"/>-->
</div>
<div id="do-login">
    <h2>Conectate usando tu cuenta de Facebook</h2>
    <? 
        $fb = Zend_Registry::get("facebook"); 
        $params = array(
            scope => 'email,publish_stream,offline_access',
            redirect_uri => 'http://www.melogaste.com/Log/save'
        );
    ?>
    <a href="<?=$fb->getLoginUrl($params)?>" class="btn large primary">Usa tu <b>Facebook</b></a>
    <div class="fb-facepile" data-width="300" data-max-rows="4"></div>
</div>
<div class="clear"></div>