<?php $this->headTitle()->append('Categorias');?>
<?php $this->form->setAction($this->url(array(
        'controller' => 'Categoria',
        'action'     => 'add'
    ),
    'default',
    true));?>
<h1>Categorias</h1>
<div id="formCat" class="normal">
    <h2>Nueva Categoria: </h2>
    <?php echo $this->form; ?>
</div>
<table class="zebra-striped" id="tabla">
    <thead>
        <tr>
            <th>Categoria</th>
            <th class="green">Ingresos</th>
            <th class="red">Egresos</th>
            <th class="blue">Balance</th>
        </tr>
    </thead>
    <tbody>
        <? $i=0; ?>
        <?php foreach($this->cat as $cat) { ?>
        <? $bal=$cat->getIngresos()-$cat->getEgresos(); ?>
        <tr id="<?=$cat->getIdCategoria();?>">
            <td class="editable"><span class="edit tooltip" title="Clic para editar" data-placement="left" id="<?=$cat->getIdCategoria();?>"><? echo $cat->getCategoria();?></span></td>
            <td class="green">$ <? echo number_format($cat->getIngresos(), 0, '', '.');?></td>
            <td class="red">$ <? echo number_format($cat->getEgresos(), 0, '', '.');?></td>
            <td class="<?=($bal>0)?"green":"red";?>">$ <?= number_format($bal, 0, '', '.'); ?></td>
        </tr>
        <? $i++; ?>
        <?php } ?>
    </tbody>
</table>