<?php $this->headTitle()->append('Transacciones');?>
<?php $this->headTitle()->append($this->categoria->nombre);?>
<h1>Transacciones</h1>
<h2 class="tooltip" data-placement="right" title="<?="$".number_format($this->categoria->ing, 0, '', '.')." - $".number_format($this->categoria->gas, 0, '', '.')." = $".number_format($this->categoria->bal, 0, '', '.'); ?>"><?=$this->categoria->nombre.": $".number_format($this->categoria->bal, 0, '', '.'); ?></h2>
<table class="zebra-striped" id="registro" style="<?=(count($this->paginator) > 0)?"":"display:none;"?>">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Categor&iacute;a</th>
            <th>Descripci&oacute;n</th>
            <th class="blue">Monto</th>
            <th class="actionCol">Acci&oacute;n</th>
        </tr>
    </thead>
    <tbody>
        <? $i=0; ?>
        <? foreach ($this->paginator as $reg) { ?>
        <tr class="<?=($i%2==0)?'impar':'par';?> <?=($i==0)?'primero':''?>" id="<?=$reg->getIdRegistro();?>">
            <td align="center"><?= $reg->getFechaRegistro(); ?></td>
            <td align="center"><?= $this->catArr[$reg->getIdCategoria()]; ?></td>
            <td><?= $this->escape((strlen($reg->getDescRegistro())>70)?substr($reg->getDescRegistro(), 0, 70)."...":$reg->getDescRegistro()); ?></td>
            <td class="<?= ($reg->getIdTipoRegistro()==1)?"green":"red" ?>">$ <?=number_format($reg->getMontoRegistro(), 0, '', '.')?></td>
            <td class="actionCol">
                <a href="#" onClick="cargaTransaccion('<?=$reg->getIdRegistro();?>'); return false;"><img src="<?=$this->baseUrl()?>/img/edit.png" alt="Editar" title="Editar transacción" border="0" width="20" class="tooltip" style="margin:0;"/></a>
                <a href="#" onClick="delTransaccion('<?=$reg->getIdRegistro();?>'); return false;"><img src="<?=$this->baseUrl()?>/img/delete.png" alt="Eliminar" title="Eliminar transacción" border="0" width="20" class="tooltip" style="margin:0;"/></a>
            </td>
        </tr>
        <? $i++; ?>
        <? } ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator,'Sliding','/partials/controls.phtml'); ?>
<!--</div>-->
<div class="clear"></div>