<?php echo $this->doctype() ?>
<?php 
    if($this->controlador != "Log") {
        $this->formReg->setAction($this->url(array(
                'controller' => 'Transaccion',
                'action'     => 'add'
            ),
            'default',
            true)); 
    }
?>
<html  xmlns:fb="http://www.facebook.com/2008/fbml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-21023768-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
    </head>
    <body>
        <div id="header">
            <div id="header-wrapper">
                <span id="logo">Me lo<br/>Gast&eacute;!</span>
                <? $me = Zend_Registry::get("me"); ?>
                <? $fb = Zend_Registry::get("facebook"); ?>
                <? if($me) { ?>
                <div id="usuario">
                    <img src="https://graph.facebook.com/<?= $me["id"]; ?>/picture" height="50">
                    <span id="name"><?=$me["name"]?></span>
                    <span id="proyecto" class="tooltip" title="<?="$".number_format($this->proyecto->getIngresos(), 0, '', '.')." - $".number_format($this->proyecto->getEgresos(), 0, '', '.')." = $".number_format($this->proyecto->getBalance(), 0, '', '.'); ?>">Proyecto <?=$this->proyecto->getNomProyecto();?>: <?="$".number_format($this->proyecto->getBalance(), 0, '', '.'); ?></span>
                </div>
                <div id="botonera">
                    <a href="#" onClick="addTransaccion(); return false;" class="btn primary"><img src="<?=$this->baseUrl()?>/img/36.png" border="0" title="Nueva Transaccion"/>Nueva Transacci&oacute;n</a>
                </div>
<!--                <div id="header-nav">
                    <div id="user-info">
                        <img src="https://graph.facebook.com/<?= $me["id"]; ?>/picture" height="26">
                        <span id="name"><?=$me["name"]?></span>
                        <div class="dropdown">
                            <ul class="unstyled">
                                <li><a href="#">Perfil</a></li>
                                <li><a href="#">Configuracion</a></li>
                                <li><a href="<?=$fb->getLogoutUrl()?>">Salir</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="proyectos-list">
                        <span id="name">Proyecto: Principal</span>
                        <div class="dropdown">
                            <ul class="unstyled">
                                <li><a href="#">Perfil</a></li>
                                <li><a href="#">Configuracion</a></li>
                                <li><a href="<?=$fb->getLogoutUrl()?>">Salir</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="invitar">
                        <img src="<?=$this->baseUrl()?>/img/share.png" />
                        <span><a onClick="invitar();">Invita a tus amigos!</a></span>
                    </div>
                </div>-->
                <? } ?>
            </div>
        </div>
        <div id="wrapper">
            <?if($me) {?>
            <div id="main-nav">
<!--                <h1 style="padding: 10px 20px; background-color: #333; display:inline-block; border-left: 20px solid #111; margin-left: -20px; color: whitesmoke;">Proyecto: Principal</h1>-->
<!--                <div class="sub-nav"><a href="#" onClick="addTransaccion(); return false;"><img src="<?=$this->baseUrl()?>/img/add.png" border="0" title="Nueva Transaccion"/>Nueva Transacci&oacute;n</a></div>-->
            </div>
                <div id="sidebar">
                    <div id="side-nav">
                        <ul class="unstyled">
                            <li><a class="<?=($this->controlador == "Index")?"active":""?>" href="<?php echo $this->url(array('controller' => 'Index', 'action' => 'index'), 'default', true) ?>"><img src="<?=$this->baseUrl()?>/img/6.png" border="0"/>Dashboard</a></li>
<!--                            <li><a class="<?=($this->controlador == "Proyecto")?"active":""?>" href="#">Proyectos</a></li>
                            <li><a class="<?=($this->controlador == "Reporte")?"active":""?>" href="#">Reportes</a></li>-->
                            <li><a class="<?=($this->controlador == "Categoria")?"active":""?>" href="<?php echo $this->url(array('controller' => 'Categoria', 'action' => 'index'), 'default', true) ?>"><img src="<?=$this->baseUrl()?>/img/35.png" border="0"/>Categor&iacute;as</a></li>
                            <li><a class="<?=($this->controlador == "Transaccion")?"active":""?>" href="<?php echo $this->url(array('controller' => 'Transaccion', 'action' => 'index'), 'default', true) ?>"><img src="<?=$this->baseUrl()?>/img/50.png" border="0"/>Transacciones</a>
                                <?php if($this->controlador == "Transaccion") { ?>
                                <ul class="unstyled">
                                    <?php foreach($this->cat as $cat) {?>
                                        <li><a class="<?=($this->id == $cat->idCategoria)?"active":""?>" href="<?php echo $this->url(array('controller' => 'Transaccion', 'action' => 'categoria', 'id'=>$cat->idCategoria), 'default', true) ?>"><?php echo $cat->categoria." "; ?></a></li>
                                    <?php } ?>
                                </ul>
                                <?php } ?>
                            </li>
                        </ul>
                    </div>
                </div>
                <div id="content">
                    <?php echo $this->layout()->content; ?>
                </div>
            <? } else {?>
                <div id="login">
                    <?php echo $this->layout()->content; ?>
                </div>
            <? } ?>
            <div class="clear"></div>
            <div id="footer">
                <p style="margin-bottom: 0; font-size: 15px;"><a href="http://www.melogaste.com">Me lo Gaste!</a> | Desarrollado por <a href="http://twitter.com/#!/Neeph" class="yo">@Neeph</a> en sus ratos de ocio =)</p>
            </div>
            <div id="formReg" class="flotando" style="display: none;">
                <h2>Nueva Transacci&oacute;n</h2><span class="btnIco popup"></span>
                <?php echo $this->formReg; ?>
            </div>
        </div>
        <div id="aire"></div>
        <div id="fb-root"></div>
        <script>
//            window.fbAsyncInit = function() {
//                FB.init({
//                    appId : '<?php echo $fb->getAppId(); ?>',
//                    status : true, // check login status
//                    cookie : true, // enable cookies to allow the server to access the session,
//                    oauth : true,
//                    xfbml : true
//                });
//            };
//            (function(d){
//             var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
//             js = d.createElement('script'); js.id = id; js.async = true;
//             js.src = "//connect.facebook.net/en_US/all.js";
//             d.getElementsByTagName('head')[0].appendChild(js);
//           }(document));
        </script>
    </body>
</html>